### ISSUE TITLE
XNS Purchased have disappeared / Part 2

### ISSUE THREAD

**Issue by MetaTireMan** [XYOracleNetwork/os#6]
Please see attached screenshot...i am able to retrieve three of the four xNS.

I was not able to retrieve "MetaTireMan.XYO"

When I had to purchase MetaTireMan it failed on the first transaction...

https://etherscan.io/tx/0x47d78ebdc85d563298f5c8b684047e9f55d643f5c60876857169904b66c23ae6

Transaction was successful, however I never received my xNS.

The next day I repurchased on a different browser.

**WHAT I NOTICED,,,
When I purchased this xNS on the FIRST transaction I was doing it on a browser my current XYO Wallet was not connected to.  The NowPayments popup modal opens up and allows me to connect my XYO wallet, however there was no association to the XYO Wallet and Public NODE.**

**The next day on my second try...I used a browser my XYO WALLET was associated to...There was no issues on this transaction.**

![Missing 1 xNS](https://github.com/XYOracleNetwork/os/assets/167895958/8e7fa32a-3ecd-4647-abe2-b4b4fc526634)

_Originally posted by @MetaTireMan in https://github.com/XYOracleNetwork/os/issues/5#issuecomment-2088468960_

**Comment by MetaTireMan** [comment]
Any update on this bug of my missing xNS "MetaTireMan"?

I know this takes time sometimes, just curious.

**Comment by JoelBCarter** [comment]
@MetaTireMan thanks for your patience on this one.  I had to do some sleuthing.  `MetaTireMan.XYO` is owned but not by the address associated with the other domains you showed.  One way to get into this situation would be like it seems you may have gotten into, which is if you started the purchase on one browser (with a different XYO wallet address) and then finished it on another browser (with a different XYO wallet address).  Currently, for purchases we initiate a time-limited escrow and use the XYO wallet that initiated the transaction as the one who we convey the domain to upon successful payment.  Otherwise, someone might be able to purchase it out from underneath of you.  We currently do not have a way to transfer a domain from one address to another (but we are working on this one) or load multiple seed-phrases in a single browser so you can manage them both.  Do you still have access to the old browser/seed-phrase?

**Comment by MetaTireMan** [comment]
I have already imported...

Like I said I purchased "MetaTireMan.XYO" twice.  The first day I purchased on a browser which had no wallet connection.

The next day I figured out it was most likely the browser issue and did everything on Chrome. See screenshot with all four xNS domains.

![image](https://github.com/XYOracleNetwork/os/assets/167895958/ad8638a6-beba-4cc0-a3d6-db72e19b7f8c)

Later that week I had to clean my browser, when I did a reimport of the seed phrase 3 of the 4 show.

![image](https://github.com/XYOracleNetwork/os/assets/167895958/0c1b3440-9086-4fd5-8c2c-f4bb58ce4816)

**Comment by MetaTireMan** [comment]
I tried seeing if I could find MetaTireMan using the BraveBroswer...Public Node address of Brave browser is: 0xb245399137c2826dc3b6c4ab91666f21a97fba51

But this browser does
Not have a connection as of right now...is this the BroswerNODE you see associated to MetaTireMan?

I tried exporting this seed phrase and importing to my phone browser node which has XYO wallet connection, still no good.

**Comment by JoelBCarter** [comment]
@MetaTireMan You're a hero.  You've done some awesome groundwork helping us determine which features we are going to prioritize.  Can you reach out to me on Discord so we can get this resolved?

**Comment by MetaTireMan** [comment]
Absolutely!

**Comment by JoelBCarter** [comment]
☝🏼 I was able to resolve this one on Discord with @MetaTireMan so I'm closing it here.
